
find . | grep "\.[hm]$" | xargs sed -i "" 's/HTight/Horizontal/'
find . | grep "\.md$" | xargs sed -i "" 's/HTight/Horizontal/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/LAYOUT_MODE_H_TIGHT/LAYOUT_MODE_HORIZONTAL/'
find . | grep "\.md$" | xargs sed -i "" 's/LAYOUT_MODE_H_TIGHT/LAYOUT_MODE_HORIZONTAL/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/HFill/HorizontalFill/'
find . | grep "\.md$" | xargs sed -i "" 's/HFill/HorizontalFill/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/LAYOUT_MODE_H_FILL/LAYOUT_MODE_HORIZONTAL_FILL/'
find . | grep "\.md$" | xargs sed -i "" 's/LAYOUT_MODE_H_FILL/LAYOUT_MODE_HORIZONTAL_FILL/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/VTight/Vertical/'
find . | grep "\.md$" | xargs sed -i "" 's/VTight/Vertical/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/LAYOUT_MODE_V_TIGHT/LAYOUT_MODE_VERTICAL/'
find . | grep "\.md$" | xargs sed -i "" 's/LAYOUT_MODE_V_TIGHT/LAYOUT_MODE_VERTICAL/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/VFill/VerticalFill/'
find . | grep "\.md$" | xargs sed -i "" 's/VFill/VerticalFill/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/LAYOUT_MODE_V_FILL/LAYOUT_MODE_VERTICAL_FILL/'
find . | grep "\.md$" | xargs sed -i "" 's/LAYOUT_MODE_V_FILL/LAYOUT_MODE_VERTICAL_FILL/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/FillLoose/Fill/'
find . | grep "\.md$" | xargs sed -i "" 's/FillLoose/Fill/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/LAYOUT_MODE_FILL_LOOSE/LAYOUT_MODE_FILL/'
find . | grep "\.md$" | xargs sed -i "" 's/LAYOUT_MODE_FILL_LOOSE/LAYOUT_MODE_FILL/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/FillTight/FillNatural/'
find . | grep "\.md$" | xargs sed -i "" 's/FillTight/FillNatural/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/LAYOUT_MODE_FILL_TIGHT/LAYOUT_MODE_FILL_NATURAL/'
find . | grep "\.md$" | xargs sed -i "" 's/LAYOUT_MODE_FILL_TIGHT/LAYOUT_MODE_FILL_NATURAL/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/TightGrid/NaturalGrid/'
find . | grep "\.md$" | xargs sed -i "" 's/TightGrid/NaturalGrid/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/LAYOUT_MODE_TIGHT_GRID/LAYOUT_MODE_NATURAL_GRID/'
find . | grep "\.md$" | xargs sed -i "" 's/LAYOUT_MODE_TIGHT_GRID/LAYOUT_MODE_NATURAL_GRID/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/LooseGrid/SpacingGrid/'
find . | grep "\.md$" | xargs sed -i "" 's/LooseGrid/SpacingGrid/'
find . | grep "\.[hm]$" | xargs sed -i "" 's/LAYOUT_MODE_LOOSE_GRID/LAYOUT_MODE_SPACING_GRID/'
find . | grep "\.md$" | xargs sed -i "" 's/LAYOUT_MODE_LOOSE_GRID/LAYOUT_MODE_SPACING_GRID/'


